POST http://localhost:8081/unidades/alterar
Content-Type: application/json

{
  "id": 1,
  "descricao": "Unidade Santo Amaro",
  "endereco": {
    "id": 1,
    "logradouro": "Rua Teste",
    "numero": 20,
    "complemento": "Teste",
    "cep": "22222-222",
    "bairro": "Teste",
    "cidade": "Teste",
    "uf": "SP"
  },
  "status": "ATIVO"
}