POST http://localhost:8081/medicos/alterar
Content-Type: application/json

{
  "id": 1,
  "nome": "Luciano Alterar",
  "cpf": "405.046.560-40",
  "crm": "2132415343",
  "endereco": {
    "id": 1,
    "logradouro": "Rua Teste2",
    "numero": "20",
    "complemento": "Teste2",
    "cep": "22222-222",
    "bairro": "Teste2",
    "cidade": "Teste2",
    "uf": "SP"
  },
  "contato": {
    "id": 1,
    "email": "luciano.teste@teste.com.br",
    "telefone": "11931010447"
  },
  "login": {
    "id": 1,
    "usuario": "luciano.teste",
    "senha": "123"
  },
  "especializacao": {
    "id": 1
  }
}
