POST http://localhost:8081/pacientes/cadastrar
Content-Type: application/json

{
  "nome": "Luciano",
  "cpf": "405.046.560-70",
  "endereco": {
    "logradouro": "Rua Teste",
    "numero": "20",
    "complemento": "Teste",
    "cep": "22222-222",
    "bairro": "Teste",
    "cidade": "Teste",
    "uf": "SP"
  },
  "contato": {
    "email": "luciano.teste2@teste2.com.br",
    "telefone": "11931010447"
  },
  "login": {
    "usuario": "luciano.teste2",
    "senha": "123"
  }
}