POST http://localhost:8081/agendamentos/cadastrar
Content-Type: application/json

{
  "dataAgendamento": [
    2023,
    11,
    15
  ],
  "horaInicio": [
    13,
    0
  ],
  "horaTermino": [
    14,
    0
  ],
  "paciente": {
    "id": 2
  },
  "medico": {
    "id": 1
  },
  "unidade": {
    "id": 1
  },
  "andamento": "AGENDADO"
}